### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by ChristianUlbrich** [mgenware/ts-transform-esm-import#7]
Somehow, this does not seem to work for me. I did:

* cloned the current repo
* `npm i`
* `npx run r build`
* `cd example`
* `npm i`
* `npx ttsc`

After that I get the transpiled output in `example/dist`, but the _JS_ files do not have any `.js` extensions whatsoever.

In a real-world project it doe not work for me either.

**Comment by mgenware** [comment]
@ChristianUlbrich Looks like the example project dependencies are not in sync with the main project. Released [0.6.0](https://github.com/mgenware/ts-transform-esm-import/releases/tag/v0.6.0) (also resolved some ts 4.5 API breaking changes). This project now relies on typescript 4.5 and ts-patch.
